/* Generated by generateAPISchemas.js */
export const APISetAgeRequestSchema = {
  type: "object",
  properties: {
    birthday: {
      description: "Enables basic storage and retrieval of dates and times.",
      type: "string",
      format: "date-time",
    },
  },
  required: ["birthday"],
  $schema: "http://json-schema.org/draft-07/schema#",
} as const;

export const APINewStoryRequestSchema = {
  type: "object",
  properties: {
    story: {
      type: "array",
      items: {
        type: "array",
        items: {
          type: "object",
          properties: {
            year: {
              minimum: 1900,
              type: "number",
            },
            month: {
              maximum: 12,
              minimum: 1,
              type: "number",
            },
            isHeartBreak: {
              type: "boolean",
            },
            intensity: {
              type: "number",
            },
          },
          required: ["intensity", "isHeartBreak", "month", "year"],
        },
      },
    },
  },
  required: ["story"],
  $schema: "http://json-schema.org/draft-07/schema#",
} as const;

export const APITestRequestSchema = {
  type: "object",
  properties: {
    foo: {
      minimum: 5,
      type: "number",
    },
  },
  $schema: "http://json-schema.org/draft-07/schema#",
} as const;
