/* Generated by generateAPISchemas.js */
export const APITestRequestSchema = {
  type: "object",
  properties: {
    foo: {
      minimum: 5,
      type: "number",
    },
  },
  $schema: "http://json-schema.org/draft-07/schema#",
} as const;
