/* eslint-disable  */
const TJS = require("typescript-json-schema");
const TSConfig = require("./tsconfig.json");
const fs = require("fs");
const glob = require("glob");

const settings = {
  required: true,
  excludePrivate: true,
};

const compilerOptions = TSConfig.compilerOptions;

glob("./src/pages/api/**/*.ts", (err, matches) => {
  const program = TJS.getProgramFromFiles(matches, compilerOptions);

  const generator = TJS.buildGenerator(program, settings);

  const symbols = generator.getMainFileSymbols(program);
  fs.writeFileSync(
    "./src/Server/apiSchemas.ts",
    "/* Generated by generateAPISchemas.js */ \n" +
      symbols
        .filter((symbol) => symbol.startsWith("API"))
        .map((symbol) => {
          const schema = generator.getSchemaForSymbol(symbol);
          return `export const ${symbol}Schema = ${JSON.stringify(
            schema,
            null,
            2
          )} as const;`;
        })
        .join("\n\n")
  );
});
